### ISSUE TITLE
Linux build error

### ISSUE THREAD

**Issue by griffin28** [NVIDIA-Omniverse/AnariUsdDevice#15]
Linux build errors encountered due to the usage of c++17 classes like `std::variant` and `std::visit` in files under the **UsdBridge** directory. Setting `CMAKE_CXX_STANDARD` to 17 in `UsdBridge\CMakeLists.txt` fixes the problem.

![usd_error_2](https://github.com/NVIDIA-Omniverse/AnariUsdDevice/assets/26772741/08fabbb9-529b-454a-8368-832c3554d80e)

**Comment by kvankooten** [comment]
Thanks, fixed in https://github.com/NVIDIA-Omniverse/AnariUsdDevice/commit/480b8af80da7c358d167bda5a6d631e2dfe21328
